USE [master]
GO
/****** Object:  Database [HRRepository]    Script Date: 11-08-2021 22:11:03 ******/
CREATE DATABASE [HRRepository]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HRRepository', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HRRepository.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HRRepository_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HRRepository_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [HRRepository] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HRRepository].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HRRepository] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HRRepository] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HRRepository] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HRRepository] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HRRepository] SET ARITHABORT OFF 
GO
ALTER DATABASE [HRRepository] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HRRepository] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HRRepository] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HRRepository] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HRRepository] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HRRepository] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HRRepository] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HRRepository] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HRRepository] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HRRepository] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HRRepository] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HRRepository] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HRRepository] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HRRepository] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HRRepository] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HRRepository] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HRRepository] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HRRepository] SET RECOVERY FULL 
GO
ALTER DATABASE [HRRepository] SET  MULTI_USER 
GO
ALTER DATABASE [HRRepository] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HRRepository] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HRRepository] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HRRepository] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HRRepository] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HRRepository] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'HRRepository', N'ON'
GO
ALTER DATABASE [HRRepository] SET QUERY_STORE = OFF
GO
USE [HRRepository]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 11-08-2021 22:11:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [varchar](150) NOT NULL,
	[Gender] [char](1) NOT NULL,
	[Age] [int] NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[EmployeesInsert]    Script Date: 11-08-2021 22:11:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- EmployeesInsert 'Chithra R',25,'F'
CREATE PROC [dbo].[EmployeesInsert]
(
@FullName		VARCHAR (15),
@AGE			INT			,
@Gender			CHAR(1)

)
As
INSERT INTO Employees
		(
			FullName,
			Age,
			Gender
		)
	VALUES
		(
			@FullName,
			@AGE,
			@Gender
		)

GO
/****** Object:  StoredProcedure [dbo].[EmployeesSelect]    Script Date: 11-08-2021 22:11:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[EmployeesSelect]
AS
SELECT EmployeeID,FullName,Age, Gender FROM Employees
order by EmployeeID desc
GO
USE [master]
GO
ALTER DATABASE [HRRepository] SET  READ_WRITE 
GO
